### PR TITLE
support metric_relabel for __name__

### PR DESCRIPTION
**Pull request by mtanda**
### What was the expected result?
Prometheus drop metrics which match pattern. 
```
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: ^foo_.*$
      action: drop
```

### What happened instead?
Prometheus can't drop the metrics.

### CODE REVIEW

**Comment by mtanda** [comment]
@jkohen Would you check this?

**Comment by jkohen** [comment]
I can reproduce, I will work on a fix. Thanks!

**Comment by mtanda** [comment]
@jkohen Thanks for quick reply and fix.
I close this PR :-)

**Comment by jkohen** [comment]
The PR hasn't been merged, yet, please don't close the issue.

**Comment by mtanda** [comment]
Oops, sorry. This is a PR. I should make an Issue first...
Anyway, I keep this PR until merging your PR.

**Comment by jkohen** [comment]
Indeed! I betrayed my lack of fluency in GitHub. Thanks for the PR 😄 mine has tests and fixes one issue with this one, so I'll keep that.

**Comment by jkohen** [comment]
Release 0.4.2 includes the fix.

**Comment by mtanda** [comment]
Thanks lot!!

**Pull request closed without merging**
